Repository dani17b/lib-productivio, pull requests merged in 2023-04, with the labels that each got.

#149 #148 Adjust Roadmap's scss
  src/components/roadmap/Roadmap.tsx
  src/components/roadmap/roadmap.scss
Labels: enhancement

#155 component exported and add icon save
  src/components/roundButton/RoundButton.tsx
  src/index.ts
Labels: documentation, enhancement

#156 #148 Roadmap quick fix
  src/components/roadmap/Roadmap.tsx
Labels: enhancement

#153 fixed optical ilusion
  src/components/taskProgressBar/TaskProgressBar.tsx
Labels: bug

#161 Component created
  src/components/userListChild/UserListChild.stories.mdx
  src/components/userListChild/UserListChild.tsx
  src/components/userListChild/userListChild.scss
  src/index.ts
Labels: enhancement

#163 151 implement level and points into profile progressbar
  src/components/profileProgressBar/ProfileProgressBar.stories.mdx
  src/components/profileProgressBar/ProfileProgressBar.tsx
  src/components/profileProgressBar/profileProgressBar.scss
Labels: enhancement

#168 166 fixed not centered issue with level and points
  src/components/profileProgressBar/ProfileProgressBar.stories.mdx
  src/components/profileProgressBar/ProfileProgressBar.tsx
  src/components/profileProgressBar/profileProgressBar.scss
Labels: bug

#176 test done
  src/components/taskProgressBar/TaskProgressBar.test.tsx
  src/components/taskProgressBar/TaskProgressBar.tsx
Labels: enhancement

#184 Likes test
  src/components/likes/Likes.test.tsx
  src/components/likes/Likes.tsx
Labels: enhancement
