Repository dani17b/lib-productivio, pull requests merged in 2023-03, with the labels that each got.

#11 Added story and documentation on TeamDropdown
  src/components/teamDropdown/TeamDropdown.tsx
  src/components/teamDropdown/teamDropdown.scss
  src/components/teamDropdown/teamDropdown.stories.mdx
Labels: documentation

#14 ProfileProgressBar component added and storybook doc created
  src/components/profileProgressBar/ProfileProgressBar.stories.mdx
  src/components/profileProgressBar/ProfileProgressBar.tsx
  src/components/profileProgressBar/profileProgressBar.scss
Labels: documentation

#20 #4 UserSummary documentation
  src/components/userSummary/UserSummary.stories.mdx
  src/components/userSummary/UserSummary.tsx
  src/components/userSummary/actions.ts
Labels: documentation

#19 Documentation for global styles and variables
  src/components/style/StyleExample.tsx
  src/components/style/fonts/Inter-VariableFont_slnt,wght.ttf
  src/components/style/global.stories.mdx
  src/components/style/styleExample.scss
  src/components/style/vars.scss
  src/components/style/vars.stories.mdx
Labels: documentation

#23 document component header in storybook
  src/components/header/Header.stories.mdx
  src/components/header/Header.tsx
  src/components/header/header.scss
Labels: documentation

#50 navBar done
  src/components/navBar/NavBar.stories.mdx
  src/components/navBar/NavBar.tsx
  src/components/navBar/navBar.scss
Labels: documentation, enhancement

#46 #42 UserPhoto implemented in UserSummary
  src/components/userSummary/UserSummary.stories.mdx
  src/components/userSummary/UserSummary.tsx
  src/components/userSummary/userSummary.scss
  src/index.ts
Labels: documentation, enhancement

#48 #41 FormButton created & documented (working)
  src/components/formButton/FormButton.stories.mdx
  src/components/formButton/FormButton.tsx
  src/components/formButton/formButton.scss
  src/index.ts
Labels: documentation, enhancement

#53 31 create top 1 in ranking
  src/components/topOne/TopOne.stories.mdx
  src/components/topOne/TopOne.tsx
  src/components/topOne/img/fireworks.png
  src/components/topOne/topOne.scss
Labels: documentation, enhancement

#44 header fixed
  src/components/header/Header.stories.mdx
  src/components/header/Header.tsx
  src/components/header/header.scss
Labels: documentation

#68 Export added
  src/index.ts
Labels: bug

#80 stylesheet follows naming convention
  src/components/inputWithLabel/InputWithLabel.tsx
  src/components/inputWithLabel/inputWithLabel.scss
Labels: documentation

#86 67 create component select dropdown menu with options
  src/components/selectMenu/SelectMenu.stories.mdx
  src/components/selectMenu/SelectMenu.tsx
  src/components/selectMenu/selectMenu.scss
Labels: documentation, enhancement

#88 Imports changed, Lib working
  src/components/searchBox/SearchBox.tsx
  src/index.ts
Labels: bug

#95 ProfileProgressBar updated
  src/components/profileProgressBar/ProfileProgressBar.stories.mdx
  src/components/profileProgressBar/ProfileProgressBar.tsx
  src/components/profileProgressBar/profileProgressBar.scss
Labels: bug

#100 79 change icons in navbar
  src/components/navBar/NavBar.stories.mdx
  src/components/navBar/NavBar.tsx
  src/components/navBar/navBar.scss
Labels: documentation, enhancement

#102 #41 formButtons new prop added & tested
  src/components/formButton/FormButton.stories.mdx
  src/components/formButton/FormButton.tsx
  src/components/formButton/formButton.scss
Labels: documentation, enhancement

#85 MissionBlock created and documented
  src/components/missionBlock/MissionBlock.stories.mdx
  src/components/missionBlock/MissionBlock.tsx
  src/components/missionBlock/missionBlock.scss
  src/components/roundButton/RoundButton.tsx
Labels: enhancement

#84 78 create userinfo component
  src/components/userInfo/UserInfo.stories.mdx
  src/components/userInfo/UserInfo.tsx
  src/components/userInfo/userInfo.scss
  src/components/userSummary/UserSummary.stories.mdx
  src/components/userSummary/UserSummary.tsx
  src/index.ts
Labels: documentation, enhancement

#105 90 create dateselect component
  package.json
  src/components/dateSelect/DateSelect.stories.mdx
  src/components/dateSelect/DateSelect.tsx
  src/components/dateSelect/dateSelect.scss
Labels: documentation, enhancement

#107 date select exported and ready to build
  src/index.ts
Labels: enhancement

#110 export Select Menu added
  src/index.ts
Labels: enhancement

#113 style updated
  src/components/selectMenu/selectMenu.scss
Labels: documentation, enhancement

#123 114 modify inputwithlabel
  src/components/formButton/FormButton.tsx
  src/components/inputWithLabel/InputWithLabel.tsx
  src/components/selectMenu/selectMenu.scss
Labels: bug, enhancement

#127 styles and props updated
  src/components/missionBlock/MissionBlock.stories.mdx
  src/components/missionBlock/MissionBlock.tsx
  src/components/missionBlock/missionBlock.scss
  src/index.ts
Labels: enhancement

#129 styles updated
  src/components/header/header.scss
  src/components/navBar/navBar.scss
Labels: bug

#134 #36 roadmap point prototype
  src/components/roadmap/Roadmap.tsx
  src/components/roadmap/roadmap.scss
  src/components/roadmap/roadmap.stories.mdx
  src/index.ts
Labels: documentation, enhancement

#138 #137 Duplicated export fixed
  src/index.ts
Labels: bug

#139 Ranking components' styles corrections
  src/components/podium/Podium.tsx
  src/components/podium/podium.scss
  src/components/topFiveUser/TopFiveUser.tsx
  src/components/topFiveUser/topFiveUser.scss
  src/components/topOne/TopOne.tsx
  src/components/topOne/topOne.scss
Labels: bug

#140 likedByMe on lib implemented
  src/components/likes/Likes.tsx
  src/components/visualComments/VisualComments.tsx
Labels: enhancement

#144 User atributtes renamed
  src/components/podium/Podium.stories.mdx
  src/components/podium/Podium.tsx
  src/components/topFiveUser/TopFiveUser.stories.mdx
  src/components/topFiveUser/TopFiveUser.tsx
  src/components/topOne/TopOne.stories.mdx
  src/components/topOne/TopOne.tsx
Labels: bug
